version: "3.9"

services:
  exchanger-db:
    image: postgres:18
    container_name: exchanger-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${EXCHANGER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${EXCHANGER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${EXCHANGER_POSTGRES_DB}
    volumes:
      - exchanger_data:/var/lib/postgresql
    networks:
      - mynetwork
    ports:
      - ${EXCHANGER_POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $EXCHANGER_POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5

  wallet-db:
    image: postgres:18
    container_name: wallet-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${WALLET_POSTGRES_USER}
      POSTGRES_PASSWORD: ${WALLET_POSTGRES_PASSWORD}
      POSTGRES_DB: ${WALLET_POSTGRES_DB}
    volumes:
      - wallet_data:/var/lib/postgresql
    networks:
      - mynetwork
    ports:
      - ${WALLET_POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $WALLET_POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  mynetwork:
    driver: bridge

volumes:
  wallet_data:
  exchanger_data: