// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/wallet/wallet.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/wallet/wallet.go -destination=internal/services/wallet/mocks/mock_wallet.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gw-currency-wallet/internal/domain/models"
	pgx_driver "gw-currency-wallet/pkg/pgx-driver"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSaverWallet is a mock of SaverWallet interface.
type MockSaverWallet struct {
	ctrl     *gomock.Controller
	recorder *MockSaverWalletMockRecorder
	isgomock struct{}
}

// MockSaverWalletMockRecorder is the mock recorder for MockSaverWallet.
type MockSaverWalletMockRecorder struct {
	mock *MockSaverWallet
}

// NewMockSaverWallet creates a new mock instance.
func NewMockSaverWallet(ctrl *gomock.Controller) *MockSaverWallet {
	mock := &MockSaverWallet{ctrl: ctrl}
	mock.recorder = &MockSaverWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaverWallet) EXPECT() *MockSaverWalletMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockSaverWallet) CreateWallet(ctx context.Context, walletID, userID uuid.UUID, currency string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, walletID, userID, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockSaverWalletMockRecorder) CreateWallet(ctx, walletID, userID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockSaverWallet)(nil).CreateWallet), ctx, walletID, userID, currency)
}

// MockSaverTransaction is a mock of SaverTransaction interface.
type MockSaverTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockSaverTransactionMockRecorder
	isgomock struct{}
}

// MockSaverTransactionMockRecorder is the mock recorder for MockSaverTransaction.
type MockSaverTransactionMockRecorder struct {
	mock *MockSaverTransaction
}

// NewMockSaverTransaction creates a new mock instance.
func NewMockSaverTransaction(ctrl *gomock.Controller) *MockSaverTransaction {
	mock := &MockSaverTransaction{ctrl: ctrl}
	mock.recorder = &MockSaverTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaverTransaction) EXPECT() *MockSaverTransactionMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockSaverTransaction) CreateTransaction(ctx context.Context, tx pgx_driver.QueryExecuter, operation *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, tx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockSaverTransactionMockRecorder) CreateTransaction(ctx, tx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockSaverTransaction)(nil).CreateTransaction), ctx, tx, operation)
}

// MockGetterWallet is a mock of GetterWallet interface.
type MockGetterWallet struct {
	ctrl     *gomock.Controller
	recorder *MockGetterWalletMockRecorder
	isgomock struct{}
}

// MockGetterWalletMockRecorder is the mock recorder for MockGetterWallet.
type MockGetterWalletMockRecorder struct {
	mock *MockGetterWallet
}

// NewMockGetterWallet creates a new mock instance.
func NewMockGetterWallet(ctrl *gomock.Controller) *MockGetterWallet {
	mock := &MockGetterWallet{ctrl: ctrl}
	mock.recorder = &MockGetterWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetterWallet) EXPECT() *MockGetterWalletMockRecorder {
	return m.recorder
}

// GetWalletsByUser mocks base method.
func (m *MockGetterWallet) GetWalletsByUser(ctx context.Context, userID uuid.UUID) ([]models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletsByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWalletsByUser indicates an expected call of GetWalletsByUser.
func (mr *MockGetterWalletMockRecorder) GetWalletsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletsByUser", reflect.TypeOf((*MockGetterWallet)(nil).GetWalletsByUser), ctx, userID)
}

// MockBalanceUpdaterWallet is a mock of BalanceUpdaterWallet interface.
type MockBalanceUpdaterWallet struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUpdaterWalletMockRecorder
	isgomock struct{}
}

// MockBalanceUpdaterWalletMockRecorder is the mock recorder for MockBalanceUpdaterWallet.
type MockBalanceUpdaterWalletMockRecorder struct {
	mock *MockBalanceUpdaterWallet
}

// NewMockBalanceUpdaterWallet creates a new mock instance.
func NewMockBalanceUpdaterWallet(ctrl *gomock.Controller) *MockBalanceUpdaterWallet {
	mock := &MockBalanceUpdaterWallet{ctrl: ctrl}
	mock.recorder = &MockBalanceUpdaterWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUpdaterWallet) EXPECT() *MockBalanceUpdaterWalletMockRecorder {
	return m.recorder
}

// DecreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) DecreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, userID uuid.UUID, currency string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseBalance", ctx, tx, userID, currency, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseBalance indicates an expected call of DecreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) DecreaseBalance(ctx, tx, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).DecreaseBalance), ctx, tx, userID, currency, amount)
}

// IncreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) IncreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, userID uuid.UUID, currency string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseBalance", ctx, tx, userID, currency, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseBalance indicates an expected call of IncreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) IncreaseBalance(ctx, tx, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).IncreaseBalance), ctx, tx, userID, currency, amount)
}
