// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/translation/translation.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/translation/translation.go -destination=internal/services/translation/mocks/mock_translation.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	pgx_driver "gw-currency-wallet/pkg/pgx-driver"
	rabbitmq "gw-currency-wallet/pkg/rabbitmq"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(ctx context.Context, body []byte, routingKey string, opts ...rabbitmq.PublishOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body, routingKey}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(ctx, body, routingKey any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body, routingKey}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), varargs...)
}

// MockBalanceUpdaterWallet is a mock of BalanceUpdaterWallet interface.
type MockBalanceUpdaterWallet struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUpdaterWalletMockRecorder
	isgomock struct{}
}

// MockBalanceUpdaterWalletMockRecorder is the mock recorder for MockBalanceUpdaterWallet.
type MockBalanceUpdaterWalletMockRecorder struct {
	mock *MockBalanceUpdaterWallet
}

// NewMockBalanceUpdaterWallet creates a new mock instance.
func NewMockBalanceUpdaterWallet(ctrl *gomock.Controller) *MockBalanceUpdaterWallet {
	mock := &MockBalanceUpdaterWallet{ctrl: ctrl}
	mock.recorder = &MockBalanceUpdaterWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUpdaterWallet) EXPECT() *MockBalanceUpdaterWalletMockRecorder {
	return m.recorder
}

// DecreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) DecreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, userID uuid.UUID, currency string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseBalance", ctx, tx, userID, currency, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseBalance indicates an expected call of DecreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) DecreaseBalance(ctx, tx, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).DecreaseBalance), ctx, tx, userID, currency, amount)
}

// IncreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) IncreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, userID uuid.UUID, currency string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseBalance", ctx, tx, userID, currency, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseBalance indicates an expected call of IncreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) IncreaseBalance(ctx, tx, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).IncreaseBalance), ctx, tx, userID, currency, amount)
}

// MockSaverWallet is a mock of SaverWallet interface.
type MockSaverWallet struct {
	ctrl     *gomock.Controller
	recorder *MockSaverWalletMockRecorder
	isgomock struct{}
}

// MockSaverWalletMockRecorder is the mock recorder for MockSaverWallet.
type MockSaverWalletMockRecorder struct {
	mock *MockSaverWallet
}

// NewMockSaverWallet creates a new mock instance.
func NewMockSaverWallet(ctrl *gomock.Controller) *MockSaverWallet {
	mock := &MockSaverWallet{ctrl: ctrl}
	mock.recorder = &MockSaverWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaverWallet) EXPECT() *MockSaverWalletMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockSaverWallet) CreateWallet(ctx context.Context, walletID, userID uuid.UUID, currency string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, walletID, userID, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockSaverWalletMockRecorder) CreateWallet(ctx, walletID, userID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockSaverWallet)(nil).CreateWallet), ctx, walletID, userID, currency)
}
