// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/exchanger/exchanger.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/exchanger/exchanger.go -destination=internal/services/exchanger/mocks/mock_exchanger.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "gw-currency-wallet/internal/domain/models"
	pgx_driver "gw-currency-wallet/pkg/pgx-driver"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGetterExchangerRates is a mock of GetterExchangerRates interface.
type MockGetterExchangerRates struct {
	ctrl     *gomock.Controller
	recorder *MockGetterExchangerRatesMockRecorder
	isgomock struct{}
}

// MockGetterExchangerRatesMockRecorder is the mock recorder for MockGetterExchangerRates.
type MockGetterExchangerRatesMockRecorder struct {
	mock *MockGetterExchangerRates
}

// NewMockGetterExchangerRates creates a new mock instance.
func NewMockGetterExchangerRates(ctrl *gomock.Controller) *MockGetterExchangerRates {
	mock := &MockGetterExchangerRates{ctrl: ctrl}
	mock.recorder = &MockGetterExchangerRatesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetterExchangerRates) EXPECT() *MockGetterExchangerRatesMockRecorder {
	return m.recorder
}

// GetExchangeRateForCurrency mocks base method.
func (m *MockGetterExchangerRates) GetExchangeRateForCurrency(ctx context.Context, from, to string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRateForCurrency", ctx, from, to)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRateForCurrency indicates an expected call of GetExchangeRateForCurrency.
func (mr *MockGetterExchangerRatesMockRecorder) GetExchangeRateForCurrency(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRateForCurrency", reflect.TypeOf((*MockGetterExchangerRates)(nil).GetExchangeRateForCurrency), ctx, from, to)
}

// GetExchangeRates mocks base method.
func (m *MockGetterExchangerRates) GetExchangeRates(ctx context.Context, base string) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRates", ctx, base)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRates indicates an expected call of GetExchangeRates.
func (mr *MockGetterExchangerRatesMockRecorder) GetExchangeRates(ctx, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRates", reflect.TypeOf((*MockGetterExchangerRates)(nil).GetExchangeRates), ctx, base)
}

// MockSaverExchanger is a mock of SaverExchanger interface.
type MockSaverExchanger struct {
	ctrl     *gomock.Controller
	recorder *MockSaverExchangerMockRecorder
	isgomock struct{}
}

// MockSaverExchangerMockRecorder is the mock recorder for MockSaverExchanger.
type MockSaverExchangerMockRecorder struct {
	mock *MockSaverExchanger
}

// NewMockSaverExchanger creates a new mock instance.
func NewMockSaverExchanger(ctrl *gomock.Controller) *MockSaverExchanger {
	mock := &MockSaverExchanger{ctrl: ctrl}
	mock.recorder = &MockSaverExchangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaverExchanger) EXPECT() *MockSaverExchangerMockRecorder {
	return m.recorder
}

// CreateExchange mocks base method.
func (m *MockSaverExchanger) CreateExchange(ctx context.Context, tx pgx_driver.QueryExecuter, exchange *models.Exchange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExchange", ctx, tx, exchange)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExchange indicates an expected call of CreateExchange.
func (mr *MockSaverExchangerMockRecorder) CreateExchange(ctx, tx, exchange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExchange", reflect.TypeOf((*MockSaverExchanger)(nil).CreateExchange), ctx, tx, exchange)
}

// MockSaverWallet is a mock of SaverWallet interface.
type MockSaverWallet struct {
	ctrl     *gomock.Controller
	recorder *MockSaverWalletMockRecorder
	isgomock struct{}
}

// MockSaverWalletMockRecorder is the mock recorder for MockSaverWallet.
type MockSaverWalletMockRecorder struct {
	mock *MockSaverWallet
}

// NewMockSaverWallet creates a new mock instance.
func NewMockSaverWallet(ctrl *gomock.Controller) *MockSaverWallet {
	mock := &MockSaverWallet{ctrl: ctrl}
	mock.recorder = &MockSaverWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaverWallet) EXPECT() *MockSaverWalletMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockSaverWallet) CreateWallet(ctx context.Context, walletID, userID uuid.UUID, currency string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, walletID, userID, currency)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockSaverWalletMockRecorder) CreateWallet(ctx, walletID, userID, currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockSaverWallet)(nil).CreateWallet), ctx, walletID, userID, currency)
}

// MockBalanceUpdaterWallet is a mock of BalanceUpdaterWallet interface.
type MockBalanceUpdaterWallet struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUpdaterWalletMockRecorder
	isgomock struct{}
}

// MockBalanceUpdaterWalletMockRecorder is the mock recorder for MockBalanceUpdaterWallet.
type MockBalanceUpdaterWalletMockRecorder struct {
	mock *MockBalanceUpdaterWallet
}

// NewMockBalanceUpdaterWallet creates a new mock instance.
func NewMockBalanceUpdaterWallet(ctrl *gomock.Controller) *MockBalanceUpdaterWallet {
	mock := &MockBalanceUpdaterWallet{ctrl: ctrl}
	mock.recorder = &MockBalanceUpdaterWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUpdaterWallet) EXPECT() *MockBalanceUpdaterWalletMockRecorder {
	return m.recorder
}

// DecreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) DecreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, userID uuid.UUID, currency string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseBalance", ctx, tx, userID, currency, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseBalance indicates an expected call of DecreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) DecreaseBalance(ctx, tx, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).DecreaseBalance), ctx, tx, userID, currency, amount)
}

// IncreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) IncreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, userID uuid.UUID, currency string, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseBalance", ctx, tx, userID, currency, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseBalance indicates an expected call of IncreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) IncreaseBalance(ctx, tx, userID, currency, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).IncreaseBalance), ctx, tx, userID, currency, amount)
}
